import 'package:execution_protocol/execution_protocol.dart';

const List<ParamFieldSpec> aesParams = <ParamFieldSpec>[
  ParamFieldSpec(
    id: 'mode',
    label: 'Mode',
    description: 'Encrypt applies AES-CBC with PKCS7 padding; decrypt reverses it.',
    type: ParamType.enumType,
    required: true,
    defaultValue: 'encrypt',
    allowedValues: <Object?>['encrypt', 'decrypt'],
    validation: ValidationRuleSet.none(),
    uiHint: UiHint.segmentedChoice,
    secret: false,
  ),
  ParamFieldSpec(
    id: 'key',
    label: 'Key',
    description: 'AES key bytes. Use 16, 24, or 32 bytes after decoding.',
    type: ParamType.string,
    required: true,
    validation: ValidationRuleSet(<ValidationRule>[
      ValidationRule(kind: ValidationRuleKind.minLength, value: 1),
    ]),
    uiHint: UiHint.secretText,
    secret: true,
    example: '00112233445566778899aabbccddeeff',
  ),
  ParamFieldSpec(
    id: 'keyFormat',
    label: 'Key Format',
    description: 'How the AES key string should be decoded into bytes.',
    type: ParamType.enumType,
    required: true,
    defaultValue: 'hex',
    allowedValues: <Object?>['text', 'hex', 'base64'],
    validation: ValidationRuleSet.none(),
    uiHint: UiHint.segmentedChoice,
    secret: false,
  ),
  ParamFieldSpec(
    id: 'iv',
    label: 'IV',
    description: 'Initialization vector for CBC mode. It must decode to 16 bytes.',
    type: ParamType.string,
    required: true,
    validation: ValidationRuleSet(<ValidationRule>[
      ValidationRule(kind: ValidationRuleKind.minLength, value: 1),
    ]),
    uiHint: UiHint.secretText,
    secret: true,
    example: '0102030405060708090a0b0c0d0e0f10',
  ),
  ParamFieldSpec(
    id: 'ivFormat',
    label: 'IV Format',
    description: 'How the IV string should be decoded into bytes.',
    type: ParamType.enumType,
    required: true,
    defaultValue: 'hex',
    allowedValues: <Object?>['text', 'hex', 'base64'],
    validation: ValidationRuleSet.none(),
    uiHint: UiHint.segmentedChoice,
    secret: false,
  ),
  ParamFieldSpec(
    id: 'inputFormat',
    label: 'Input Format',
    description: 'How the payload should be decoded before AES runs.',
    type: ParamType.enumType,
    required: true,
    defaultValue: 'text',
    allowedValues: <Object?>['text', 'hex', 'base64'],
    validation: ValidationRuleSet.none(),
    uiHint: UiHint.segmentedChoice,
    secret: false,
  ),
  ParamFieldSpec(
    id: 'outputFormat',
    label: 'Output Format',
    description: 'How the resulting bytes should be rendered after AES completes.',
    type: ParamType.enumType,
    required: true,
    defaultValue: 'base64',
    allowedValues: <Object?>['text', 'hex', 'base64'],
    validation: ValidationRuleSet.none(),
    uiHint: UiHint.segmentedChoice,
    secret: false,
  ),
];
