name: persistence_drift
publish_to: none
environment:
  sdk: ^3.4.0

dependencies:
  drift: ^2.22.1
  execution_protocol:
    path: ../execution_protocol
  sqlite3: ^2.7.4
  recipe_domain:
    path: ../recipe_domain

dev_dependencies:
  drift_dev: ^2.22.1
  lints: ^5.1.1
  test: ^1.25.15
  build_runner: ^2.4.15
