name: executor_broker
publish_to: none
environment:
  sdk: ^3.4.0

dependencies:
  execution_protocol:
    path: ../execution_protocol
  recipe_domain:
    path: ../recipe_domain
  operation_registry:
    path: ../operation_registry
  executor_isolate:
    path: ../executor_isolate

dev_dependencies:
  lints: ^5.1.1
  pack_core_text:
    path: ../pack_core_text
  test: ^1.25.15
