import 'package:execution_protocol/execution_protocol.dart';

const List<ParamFieldSpec> desParams = <ParamFieldSpec>[
  ParamFieldSpec(
    id: 'mode',
    label: 'Mode',
    description: 'Encrypt applies legacy DES with PKCS7 padding; decrypt reverses it.',
    type: ParamType.enumType,
    required: true,
    defaultValue: 'encrypt',
    allowedValues: <Object?>['encrypt', 'decrypt'],
    validation: ValidationRuleSet.none(),
    uiHint: UiHint.segmentedChoice,
    secret: false,
  ),
  ParamFieldSpec(
    id: 'key',
    label: 'Key',
    description: 'DES key text. It must be exactly 8 characters long.',
    type: ParamType.string,
    required: true,
    validation: ValidationRuleSet(<ValidationRule>[
      ValidationRule(kind: ValidationRuleKind.minLength, value: 8),
      ValidationRule(kind: ValidationRuleKind.maxLength, value: 8),
    ]),
    uiHint: UiHint.secretText,
    secret: true,
    example: 'Secr3tK!',
  ),
  ParamFieldSpec(
    id: 'inputFormat',
    label: 'Input Format',
    description: 'Encrypt expects text input. Decrypt expects Base64 or text cipher text.',
    type: ParamType.enumType,
    required: true,
    defaultValue: 'text',
    allowedValues: <Object?>['text', 'base64'],
    validation: ValidationRuleSet.none(),
    uiHint: UiHint.segmentedChoice,
    secret: false,
  ),
  ParamFieldSpec(
    id: 'outputFormat',
    label: 'Output Format',
    description: 'Encrypt usually renders Base64. Decrypt usually renders text.',
    type: ParamType.enumType,
    required: true,
    defaultValue: 'base64',
    allowedValues: <Object?>['text', 'base64'],
    validation: ValidationRuleSet.none(),
    uiHint: UiHint.segmentedChoice,
    secret: false,
  ),
];
