name: pack_core_format
publish_to: none
environment:
  sdk: ^3.4.0

dependencies:
  execution_protocol:
    path: ../execution_protocol
  pack_learning_content:
    path: ../pack_learning_content

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
